name: coloncare
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  firebase_auth:
  cloud_firestore: ^6.1.1
  http:

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it:
  get:

  # Navigation
  go_router: ^13.1.0

  # Utils
  intl: ^0.19.0
  dartz:
  image_picker:
  image:

  # UI
  google_nav_bar: ^5.0.7
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0


  # local storage
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/gifs/
    - assets/icons/
    - assets/fonts/
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf